config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get 'refresh_messages', to: 'messages#refresh', as: 'refresh_messages'

  resources :users, only: %i[show] do
    resources :journeys, only: %i[destroy]
  	resources :groups, only: %i[show] do

      resources :messages, only: %i[index new create index]
  	end
  end

  resources :groups, only: [] do
    resources :journeys, only: %i[create]
  end

  resources :journey_matches, only: %i[new create] do
    get :find, on: :collection
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :start_location, class_name: 'Location'
  belongs_to :end_location, class_name: 'Location'

  has_many :journeys, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :users, through: :journeys
end

app/models/journey.rb
class Journey < ApplicationRecord
  belongs_to :user
  belongs_to :group

  def time_zone
    diference_in_minutes.to_i
  end
end

app/models/journey_match.rb
class JourneyMatch
  include ActiveModel::Model

  attr_accessor :start_at, :start_hour, :start_minute, :departure_address, :destination_address, :diference_in_minutes

  # def start_at
  #   # DateTime.parse(Date.today.to_s + " #{start_hour}:#{start_minute}")
  #   Time.new(Time.current.year, Time.current.month, Time.current.day, start_hour.to_i, start_minute)
  # end

  def time_zone
    diference_in_minutes.to_i / 60
  end

  def start_at_date
    DateTime.parse(start_at)
  end
end

app/models/location.rb
class Location < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :journeys, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :groups, through: :journeys
  after_create :send_welcome_email

  def upcoming_journey?
    if journeys.last
      journeys.last.group.start_at > Time.current - journeys.last.time_zone.hours
    else
      false
    end
  end

  def current_journeys
    if journeys.last
      current_journeys = []
      journeys.all.each do |journey|
        current_journeys.push(journey) if journey.group.start_at > Time.current - journey.time_zone.hours
      end
      current_journeys
    else
      false
    end
  end

  private

  def send_welcome_email
    UserMailer.send("welcome_email", self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def show
    @group = Group.find(params[:id])
    @message = Message.new
    @journey = Journey.find_by(user_id: current_user, group_id: params[:id])

    @markers = [
      {
        lat: @group.start_location.latitude,
        lng: @group.start_location.longitude
      },
      {
        lat: @group.end_location.latitude,
        lng: @group.end_location.longitude,
        image_url: helpers.asset_url('flag.svg')
      }
    ]
  end
end

app/controllers/journey_matches_controller.rb
class JourneyMatchesController < ApplicationController
  def new
    @journey_match = JourneyMatch.new
  end

  def create
    @journey_match = JourneyMatch.new(journey_matches_params)

    # location_params = {
    #   start_at:       @journey_match.start_at
    #   # start_location: Location.near([45, 45], 0.3),
    #   # end_location:   Location.near('16 Villa Gaudelet, Paris', 0.3)
    # }
    groups = Group.where(start_at: (@journey_match.start_at_date - 15.minutes)..(@journey_match.start_at_date + 15.minutes))
    location_start = Location.find_or_create_by(address: @journey_match.departure_address)
    location_end = Location.find_or_create_by(address: @journey_match.destination_address)

    group_find(groups, location_start, location_end)

    create_group!(location_start, location_end) unless @group

    journey = Journey.new(group: @group, user: current_user, diference_in_minutes: @journey_match.diference_in_minutes)
    journey.save
    redirect_to user_group_path(current_user, @group)
  end

  def find
    @journey_match = JourneyMatch.new(journey_matches_params)

    groups = Group.where(start_at: (@journey_match.start_at_date - 15.minutes)..(@journey_match.start_at_date + 15.minutes))
    location_start = Location.find_or_create_by(address: @journey_match.departure_address)
    location_end = Location.find_or_create_by(address: @journey_match.destination_address)

    @group = group_find(groups, location_start, location_end)

    respond_to { |format| format.js }
  end

  private

  def create_group!(location_start, location_end)
    @group = Group.new(
      start_at: @journey_match.start_at_date,
      start_location: location_start,
      end_location: location_end
    )
    @group.save
  end

  def group_find(groups, location_start, location_end)
    groups.each do |group|
      Location.near([location_start.latitude, location_start.longitude], 0.3).each do |start_location|
        next unless start_location == group.start_location
        Location.near([location_end.latitude, location_end.longitude], 0.3).each do |end_location|
          next unless end_location == group.end_location
          @group = group
          break
        end
        break
      end
      break if @group
    end
    @group
  end

  def journey_matches_params
    # params[:start_time] = "#{params['journey_match']['start_time(4i)']}:#{params['journey_match']['start_time(5i)']}"
    params.require(:journey_match).permit(:start_at, :departure_address, :destination_address, :diference_in_minutes)
  end
end

app/controllers/journeys_controller.rb
class JourneysController < ApplicationController
  def destroy
    @journey = Journey.find(params[:id])
    @journey.destroy

    redirect_to current_user
  end

  def create
    @group = Group.find(params[:group_id])
    @journey = Journey.new(group: @group, user: current_user)
    @journey.save
    flash[:notice] = "You joined a group."

    redirect_to user_group_path(current_user, @group)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @group = Group.find(params[:group_id])
    @message = Message.new
    @messages = Message.all
  end

  def create
    @message = Message.new(message_params)
    @message.group_id = params[:group_id]
    @message.user = current_user

    if @message.save
      redirect_to user_group_messages_path(current_user, current_user.journeys.last.group)
    end
  end

  def refresh
    @group = Group.find(params[:group_id])
  end

  private

  def message_params
    params.require(:message).permit(:subject)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/show.html.erb
<% content_for :title, "group show page" %>
<div class="mb-3" id="map" style="width: 100%; height: 176px;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
<div class="container px-5">
  <dl>
    <dt>from</dt>
    <dd><%=  @group.start_location.address %></dd>
    <dt>to</dt>
    <dd><%=  @group.end_location.address %></dd>
    <dt>at</dt>
    <dd><%= @group.start_at.strftime('%l:%M%p') %> <strong>in <%= distance_of_time_in_words(@group.start_at, Time.current - @group.journeys.last.time_zone.hours) %></strong></dd>
  </dl>
  <p><%= pluralize(@group.journeys.count, 'person') %> going on this trip</p>

  <p>
    <%= link_to "Share with a friend", 'javascript:void(0)', id: 'link', class: "btn btn-block btn-outline-primary"%>
  </p>
  <% if @journey.present? %>
    <p>
      <%= link_to "Chat with other members", user_group_messages_path(current_user, current_user.journeys.last.group), class: "btn btn-block btn-outline-primary"%>
    </p>
    <p>
      <%= link_to "leave group", user_journey_path(current_user, @journey), class: "btn btn-block btn-outline-danger", method: "DELETE", :data => {:confirm => 'Are you sure?'} %>
    </p>
  <% else %>
    <p>
      <%= link_to "Join group", group_journeys_path(@group), class: "btn btn-block btn-success", method: "POST" %>
    </p>
  <% end %>
</div>

app/views/journey/destroy.html.erb
<h1>Journey#dedestroy</h1>
<p>Find me in app/views/journey/dedestroy.html.erb</p>

app/views/journey_matches/_show.html.erb
<!--<p><%= journey_match.inspect %></p>-->
<% if group %>

<p>you have a match with an existing group</p>
there are <%= pluralize(group.users.count, 'person') %>
going to <%= group.start_location.address.split(',')[0] %>
from <%= group.end_location.address.split(',')[0] %>
at <%= group.start_at.strftime('%A, %b %d') %>

<%= link_to "Search again?", 'javascript:void(0)', class: "btn btn-block btn-primary trigger-find-journey" %>
<%= link_to "Join group", group_journeys_path(group), class: "btn btn-block btn-success", style: 'min-width: 136px', method: "POST" %>

<% else %>

No group found
<%= link_to "Search again?", 'javascript:void(0)', class: "btn btn-block btn-primary trigger-find-journey" %>
<%= submit_tag "Create group", class: "btn btn-block btn-success", style: 'min-width: 136px' %>

<% end %>

app/views/journey_matches/find.js.erb
var journeyMatchDisplay = document.querySelector('#journey-match-display');
var journeyMatchShow = '<%= j render "journey_matches/show", journey_match: @journey_match, group: @group %>'
journeyMatchDisplay.innerHTML = journeyMatchShow;

app/views/journey_matches/new.html.erb
<% content_for :title, "find or create a journey" %>
<div class="container pt-3 px-5">
  <div class="row justify-content-center">
    <div class="col-sm-6">

      <h1>Match a group</h1>

      <p>
        <!--      <%= link_to 'Find', find_journey_matches_path(
          journey_match: {
            departure_address: 'Ladeira Da Gloria, 26- Gloria, Rio De Janeiro - RJ',
            destination_address: 'Ladeira Da Gloria, 26- Gloria, Rio De Janeiro - RJ',
            start_hour: '17',
            start_minute: '00',
            diference_in_minutes: '180'
          }
        ), class: 'btn btn-info', remote: true %>
  -->

        <%= simple_form_for @journey_match do |f| %>
        <%= f.input :departure_address, label: 'from', input_html: { class: 'algolia-address' } %>
        <%= f.input :destination_address, label: 'to', input_html: { class: 'algolia-address' } %>
        <%= f.input :start_at, as: :string, required: false, input_html: {class: "datepicker form-group"} %>


        <!-- <%= f.input :start_hour, collection: 0..23 %>
          <%= f.input :start_minute, collection: [0, 30] %> -->
        <%= f.input :diference_in_minutes, as: :hidden %>
        <div id="journey-match-display" class="white">
          <%= link_to "Find Group", 'javascript:void(0)', class: "btn btn-block btn-primary trigger-find-journey" %>
        </div>
        <% end %>
      </p>
    </div>
  </div>
</div>

  <% content_for :after_js do %>

  <script src="https://cdn.jsdelivr.net/npm/places.js@1.17.1"></script>
  <script type="text/javascript">

    const initTimeOffsetGet = () => {
      var now = new Date();
      return now.getTimezoneOffset() / 60;
    };

    const timeZoneInput = document.getElementById('journey_match_diference_in_minutes');
    timeZoneInput.value = initTimeOffsetGet();

    document.querySelectorAll('.algolia-address').forEach((field) => {
      places({
        appId: 'plKNZFGE3Z4R',
        apiKey: '82a5e9380dac1c2b344041331f5842d9',
        container: field
      })
    });
  </script>

  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag asset_path('background-3.png') %>
    <title>MoveWithMe | <%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>

<body class="main">
  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>
  <div class="content">
    <%= yield %>
  </div>
  <%= render 'shared/footer' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
  <%= yield :after_js %>
</body>

</html>

app/views/messages/index.html.erb
<% content_for :title, "group chat messages" %>
<div class="container-scroolbar white" id="messages-container">
  <ul class="timeline">
    <% if @group.messages %> <% @group.messages.each do |message| %>

    <li>
      <p class="string optional">
        <%= message.user.email.split("@")[0] %>
      </p>
      <small
        class="time-offset-display float-right"
        data-created-at="<%= message.created_at.iso8601 %>"
      ></small>
      <h5>'<%= message.subject %>'</h5>
    </li>
    <% end %> <% end %>
  </ul>
</div>
<%= simple_form_for [current_user, @group, @message] do |f| %>
  <%= f.input :subject, class: "col-sm-10" %> <%= f.submit ">>", class: "btn btn-info" %>
<% end %>

<%= link_to "I am hidden", refresh_messages_path(group_id: @group.id), remote: true, method: 'GET', id: "secret-btn", style: 'visibility: hidden; height: 0px; display: block' %>

<% content_for :after_js do %>
  <script>
    const secretBtn = document.getElementById("secret-btn");
    const interval = setInterval(function() {
      const chat = document.querySelector("#messages-container");
      // method to be executed;

      secretBtn.click();
      chat.scrollBy(0, 1000);
    }, 3000);
  </script>
<% end %>

app/views/messages/refresh.js.erb
var msgContainer = document.getElementById("messages-container");

var generatedHTML = "<ul class='timeline'> <% if @group.messages %><% @group.messages.each do |message| %><li><p class='string optional'><%= message.user.email.split("@")[0] %></p><small class='time-offset-display float-right' data-created-at='<%= message.created_at.iso8601 %>'></small><h4>'<%= message.subject %>'</h4></li><% end %><% end %></ul>"

msgContainer.innerHTML = generatedHTML;

var timeOffsetDisplays = document.querySelectorAll('.time-offset-display');

timeOffsetDisplays.forEach((display) => {
  display.innerText = timeLocal(display);
})

// console.log(window.timeLocal())

app/views/pages/home.html.erb
<% content_for :title, "landing page" %>
<div class="banner bg-primary col-sm-12">
  <div class="banner-content text-center">
    <h1 class="text-light">Walk safer by Walking with others!</h1>
    <p class="text-light">Let us all take responsibility for freeing our communities of crime and violence.</p>
    <%= link_to "Group Up", new_journey_match_path, class: "btn btn-lg btn-light font-weight-bold wave btn-outline-primary"  %>
  </div>
</div>
<div class="card text-center">
  <div class="card-body">
    <h2 class="card-title">Walk with others and stay safe.</h5>
      <p class="card-text">Let us all take responsibility for freeing our communities of crime and violence. Let us not
        rob ourselves of the freedom which we have so recently won by allowing these evils to continue. Every community
        in
        any country has a fundamental right to be free from fear. Each and every human being has the right to feel
        secure
        in their home, to feel safe in the cities, towns and rural areas. People should not fear the night. They must be
        able to travel to work, to school and other places without danger.</p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="card-footer text-muted text-center">
  <copyright>&copy; MoveWithMe 2021</copyright>
</div>

app/views/shared/_navbar.html.erb
<header
  class="navbar <%= current_page?(root_path) ? "fixed-top" : "" %> navbar-expand navbar-dark flex-column flex-md-row bd-navbar">
  <ul class="navbar-nav bd-navbar-nav flex-row">
    <li class="nav-item">
      <% if current_page?(root_path) %>
      <a class="nav-link active " href="/">MoveWithMe</a>
      <% else %>
      <a class="nav-link" href="/">MoveWithMe</a>
      <% end %>
    </li>
    <% if !user_signed_in? %>
    <li class="nav-item">
      <% if current_page?(new_user_session_path) %>
      <%= link_to "Log in", new_user_session_path, class: "nav-link active" %>
      <% else %>
      <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
      <% end %>
    </li>
    <% else %>
    <% if current_page?(current_user) %>
    <li class="nav-item">
      <%= link_to "Groups", current_user, class: "nav-link active" %>
      <% else %>
      <%= link_to "Groups", current_user, class: "nav-link" %>
      <% end %>
    <li>
      <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
    </li>
    <% end %>
  </ul>
</header>

app/views/users/show.html.erb
<% content_for :title, "all pending groups" %>
<div class="container banner">
  <div class="row">
    <div class="col-sm-12">
      <div class="banner-content text-center">
        <h1 class="mt-5"><%= current_user.email.split("@")[0].capitalize %></h1>
          <% if current_user.upcoming_journey? %>
            <dl>
              <% next_journey = current_user.journeys.last %>
              <dt class="text-left">
                <h3>You have a trip</h3>
              </dt>
              <dd>
                <div class="card">
                  <p>
                    <%= pluralize(next_journey.group.users.count - 1, 'person') %>
                    going with you
                    to
                    <%= link_to next_journey.group.end_location.address,user_group_path(current_user, current_user.journeys.last.group) %>
                    in <%= distance_of_time_in_words(Time.current - next_journey.time_zone.hours, next_journey.group.start_at) %>
                    - <%= (next_journey.group.start_at).strftime('%l:%M%p') %>
                  </p>
                </div>
              </dd>
              <dt class="text-left">
                <h3>Your next journeys</h3>
              </dt>
              <dd>
                <% current_user.current_journeys.each do |journey| %>
                  <div class="card">
                    <%= pluralize(journey.group.users.count - 1, 'person') %>
                    going with you
                    to <%= link_to journey.group.end_location.address,user_group_path(current_user, journey.group) %>
                    <%= (journey.group.start_at).strftime('%l:%M%p') %>
                  </div>
                <% end %>
              </dd>
            </dl>
          <% else %>
            <h4>You don't have a trip</h4>
            <p>Why don't you create one</p>
            <%= link_to 'Create a trip', new_journey_match_path, class: "btn btn-lg btn-primary" %>
          <% end %>

      </div>
    </div>
  </div>
</div>